= Parameters

The parent key for all of the following parameters is `capi_core`.

== `namespace`

[horizontal]
type:: string
default:: `syn-cluster-api`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dict
default:: See `class/defaults.yml`

The default Docker image location and tag to use for the CAPI core component (key `capi-core`).

Entries in this dict should be dictionaries with keys `registry`, `image`, and `tag`. This structure provides the basis for dependency maintenance with Renovate.

The value of `capi-core.tag` in this dict is used by the component to select the version of the upstream CAPI core components.

== `variables`

[horizontal]
type:: dict
default:: `{}`

An object with environment variables that the generated manifests will be templated with, similar to `clusterctl`.
Variables should be specified in the format:

[source,yaml]
----
variables:
  FOO: bar
----

== `kubeconfig`

This parameter configures the user kubeconfig server.
See the xref:how-tos/user-kubeconfig.adoc[how-to] for step by step instructions to configure the server.

=== `serverURL`

[horizontal]
type:: string
default:: `""`

The host name on which to expose the user kubeconfig server.
If left empty, the user kubeconfig server isn't deployed.

=== `apiURL`

[horizontal]
type:: string
default:: `""`

This parameter can be set to a more user-friendly URL for the Kubernetes API server.
If this parameter is left as the empty string, the user kubeconfig is rendered with the API server URL as provisioned by Cluster API.

[NOTE]
====
The functionality of this parameter depends on the options available through the CAPI control plane provider for each individual cluster.
====

=== `ingress`

[horizontal]
type:: object
default:: `{}`

Configuration for the `Ingress` object which exposes the user kubeconfig server.
The component always overrides any user-supplied values for `metadata.name`, `metadata.namespace` and `spec.rules`.

=== `oidc`

[horizontal]
type:: object
default::
+
[source,yaml]
----
issuerURL: ""
clientId: ""
----

Currently, the component unconditionally renders a user kubeconfig that's suitable for OIDC authentication with the `kubectl` https://github.com/int128/kubelogin[kubelogin] plugin.
The component uses the values provided in this parameter as values for flags `--oidc-issuer-url` and `--oidc-client-id` for the `kubectl oidc-login get-token` call.

NOTE: The component will raise an error if either of the fields is empty.

== Example

[source,yaml]
----
namespace: example-namespace
images:
  capi-core:
    tag: v1.14.0
variables:
  SOME_VAR: value
----
